### PR TITLE
Fixing the text input not being interactive since iOS 11

### PR DESCRIPTION
**Pull request by dzenbot**
#### PR Summary
On iOS 11, both, `UIToolbar` and `UINavigationBar` have significantly changed internally, with a complete different view hierarchy, causing subclasses to behave strangely. In this case, there were new views laying above **SLKTVC**'s outlets. Even tho https://github.com/slackhq/SlackTextViewController/pull/621 fixed it, it was more like a patch, causing us to bring **SLKTVC** outlets on front of every thing else, constantly.

Instead, we're making `SLKTextInputbar` a UIView subclass instead of `UIToolbar`. The only real reason why this has always been a UIToolbar subclass is because we wanted to mimic the same native look and feel of bottom bars, with the same background color and hairline.

Please gives this a try, and let us know of any issues with this fix asap, since this is the major bottleneck for fixing other iOS 11 bug related bugs.

#### Related Issues
Fixes https://github.com/slackhq/SlackTextViewController/issues/604
Closes https://github.com/slackhq/SlackTextViewController/pull/621

### CODE REVIEW

**Comment by abildgaard** [comment]
Looks good to me in our application --

**Comment by lauracpierre** [comment]
Did a few checks, but not many OS versions
iPod, iOS 9.3.5 ✅
iPhone 6, iOS 10.3.1 ✅
iPhone 7, iOS 10.3.1  ✅
iPhone 7Plus, iOS 10.3.1  ✅
iPhone 7Plus, iOS 11  ✅
iPad Air 2, iOS 11 ✅

**Comment by lauracpierre** [comment]
Yes, sorry forgot to mention that

**Comment by lauracpierre** [comment]
You weren't kidding 😅

**Comment by abildgaard** [comment]
Thank you !!

**Comment by JFejza** [comment]
Works on our app too, at least on all iOS 11 simulators. Thanks for the fix! Will check the thread for the official release.

**Comment by DennisMostajo** [comment]
Hi everyone, I have the same issue on iOS 11, I updated my pod file to:
`pod 'SlackTextViewController' ,:git => 'https://github.com/slackhq/SlackTextViewController'`
and I tried too with:
`pod 'SlackTextViewController', :git => 'https://github.com/slackhq/SlackTextViewController.git', :branch => 'master'`
, and the Text Field input stills untouchable, the keyboard is not working or showing, I print logs if isUserInteractionEnabled and show me, YES, any help, please? thanks!

**Comment by coolcool1994** [comment]
Yeah this fixed it for us: https://github.com/Recfive/SlackTextViewController/commit/2b4cee5acfdf13e194b05459090edda6da9612a6

**Pull request merged**
