### PR TITLE
Fix coordinate system conversion

### PR DESCRIPTION
**Pull request by ikesyo**
My container view controller use case was broken from v1.4.1. 

This fixes the use case, but might break other cases. Please review it. :pray:

### CODE REVIEW

**Comment by sprynmr** [comment]
I believe I will be fixing this shortly with my iPad modal fix.

**Comment by ikesyo** [comment]
@dzenbot @sprynmr I confirmed the behavior with its latest release (v1.5), but it is still broken for our use case.

1st image: Keyboard is hidden, and the area inside the red square is a container view controller.

keyboard_is_hidden

2nd image: Keyboard is shown, but text input bar is under the keyboard.

keyboard_is_shown

**Comment by ikesyo** [comment]
If I comment out [this line](https://github.com/slackhq/SlackTextViewController/blob/e3e5b4a13b8b9a52a499a05f3c52e447f73b8af5/Source/Classes/SLKTextViewController.m#L526), it works.

**Comment by ikesyo** [comment]
Additional info: I confirmed the behaviors both in iOS 7 and iOS 8.

**Comment by sprynmr** [comment]
I'll take a look. 

Bob Spryn
Thumb Works




On Thu, Mar 5, 2015 at 10:45 PM -0800, "Syo Ikeda" <notifications@github.com> wrote:












Additional info: I confirmed the behaviors both in iOS 7 and iOS 8.

**Pull request closed without merging**
